
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/zhxy?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  mvc:
    contentnegotiation:
      # 关闭favicon
      favor-parameter: false


# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'com.ziheng.zhxy'
      paths-to-match: '/**'
      packages-to-scan: com.ziheng.zhxy

server:
  port: 8989

#文件上传位置
upload:
  path: D:/newjavaproject/projectFileSavePath/zhxy/userAvatar

#logging:
#  level:
#    root: debug

