version: "3"
services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - /root/zhxy/nginx/html:/usr/share/nginx/html
      - /root/zhxy/nginx/nginx.conf:/etc/nginx/nginx.conf
    privileged: true

  mysql:
    image: mysql:8.0.31
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql_data:/root/zhxy/data/mysql
      - /root/zhxy/zhxy.sql:/docker-entrypoint-initdb.d/zhxy.sql

  vueblog:
    image: vueblog:latest
    build: .
    ports:
      - 8989:8989
    depends_on:
      - mysql
